TARGET := test-generic.ihx
SOURCES := main.c stm8l10x_it.c \
	stm8l10x_clk.c

INCDIR := . ../../lib/STM8L10x_StdPeriph_Driver/inc
VPATH := . ../../lib/STM8L10x_StdPeriph_Driver/src/

all: $(TARGET)

-include ../apps.mk
